_projectName: miguelp
project: 
  title: 
  description: 
  image: 
    type: '\*'
  video: 
  tags: 
certification: 
  title: 
  description: 
  image: 
    type: '\*'
experience: 
  title: 
  description: 
award: 
  title: 
  description: 
link: 
  title: 
  description: 
blogEntry: 
  title: 
  description: 
  image: 
    type: '\*'
  video: 
  tags: 
  content: 
toDo: 
  title: 
  description:    