projectName: myProject1
tables: 
  content: 
    columns: 
      name: 
        type: 255
      value: 
        type: 1024
    permisions: /.*/
    show: name
  gallery: 
    columns: 
      title: 
        permisions: bla3
        type: 255
      image: 
        permisions: bla3
        type: \*
    permisions: bla1
  customer: 
    columns: 
      name: 
        permisions: bla3
        type: 255
      email: 
        permisions: bla3
        type: 255
      phone: 
        permisions: bla3
        type: 255
    show: name
  estado: 
    columns: 
      customer: 
        permisions: bla3
        type: customer
      fecha: 
        permisions: bla3
        type: date
    permisions: bla1