projectName: myProject1
tables: 
  content: 
    columns: 
      name: 
        type: 255
      value: 
        type: 1024
    permissions_create: /.*/
    permissions_read: /System Administrator/
    permissions_update: /.*/
    permissions_delete: /.*/
    show: name
  gallery: 
    columns: 
      title: 
        type: 255
      image: 
        type: \*
  customer: 
    columns: 
      name: 
        type: 255
      email: 
        type: 255
      phone: 
        type: 255
    show: name
  estado: 
    columns: 
      customer: 
        type: customer
      fecha: 
        type: date