projectName: myProject1
tables: 
  content: 
    columns: 
      name: 
        type: 255
        permissions_create: -
        permissions_read: -
      value: 
        type: 1024
        permissions_create: -
        permissions_read: -
    permissions_create: -
    permissions_read: -
    permissions_update: /.*/
    permissions_delete: /.*/
    show: name
  gallery: 
    columns: 
      title: 
        type: 255
      image: 
        type: \*
  service: 
    columns: 
      name: 
        type: 255
      image: 
        type: \*
  client: 
    columns: 
      name: 
        type: 255
      description: 
        type: 255
  statistics: 
    columns: 
      name: 
        type: 255
      value: 
        type: 255
  blog: 
    columns: 
      title: 
        type: 255
      date: 
        type: date
      summary: 
        type: 255
      body: 
        type: 255
      image: 
        type: \*