#DROP DATABASE IF EXISTS maker_mike;
CREATE DATABASE IF NOT EXISTS maker_mike;
USE maker_mike;
CREATE TABLE IF NOT EXISTS project(id int NOT NULL AUTO_INCREMENT, name varchar(255), config JSON, description varchar(255), primary key(id));
CREATE TABLE IF NOT EXISTS settings(id int NOT NULL AUTO_INCREMENT, name varchar(255), value varchar(255), primary key(id));
CREATE TABLE IF NOT EXISTS user_type(id int NOT NULL AUTO_INCREMENT, name varchar(255), landing_page varchar(255), primary key(id));
CREATE TABLE IF NOT EXISTS user(id int NOT NULL AUTO_INCREMENT, user varchar(255), pass varchar(255), type int, foreign key(type) references user_type(id), primary key(id));

INSERT INTO user_type(id, name, landing_page) VALUES (1, 'System Administrator', 'index.php') ON DUPLICATE KEY UPDATE id = id;
INSERT INTO user_type(id, name, landing_page) VALUES (2, 'User', 'index.php') ON DUPLICATE KEY UPDATE id = id;
INSERT INTO user(id, user, pass, type ) VALUES (1, 'admin',  'admin', 1) ON DUPLICATE KEY UPDATE id = id;
INSERT INTO user(id, user, pass, type ) VALUES (2, 'user',  'user', 2) ON DUPLICATE KEY UPDATE id = id;
INSERT INTO project(id, config) VALUES (1, '{"user": {"pass": {"type": "255", "_show": "Pass", "permissions_read": "System Administrator", "permissions_create": "System Administrator", "permissions_update": "System Administrator"}, "type": {"type": "user_type", "_show": "Type", "permissions_read": "System Administrator", "permissions_create": "System Administrator", "permissions_update": "System Administrator"}, "user": {"type": "255", "_show": "User", "permissions_read": "System Administrator", "permissions_create": "System Administrator", "permissions_update": "System Administrator"}, "_show": "user", "_permissions": {"read": "System Administrator", "create": "System Administrator", "delete": "System Administrator", "update": "System Administrator"}}, "_show": "Maker Mike", "project": {"name": {"type": "255", "_show": "Name", "permissions_read": "-", "permissions_create": ".*", "permissions_update": ".*"}, "_show": "name", "config": {"type": "JSON", "_show": "Config", "permissions_read": "-", "permissions_create": ".*", "permissions_update": ".*"}, "description": {"type": "255", "_show": "Description", "permissions_read": "-", "permissions_create": ".*", "permissions_update": ".*"}, "_permissions": {"read": ".*", "create": ".*", "delete": ".*", "update": ".*"}}, "settings": {"name": {"type": "255", "_show": "Name", "permissions_read": "-", "permissions_create": ".*", "permissions_update": ".*"}, "_show": "name", "value": {"type": "255", "_show": "Value", "permissions_read": "-", "permissions_create": ".*", "permissions_update": ".*"}, "_permissions": {"read": ".*", "create": ".*", "delete": ".*", "update": ".*"}}, "user_type": {"name": {"type": "255", "_show": "Name", "permissions_read": "System Administrator", "permissions_create": "System Administrator", "permissions_update": "System Administrator"}, "_show": "name", "_permissions": {"read": "System Administrator", "create": "System Administrator", "delete": "System Administrator", "update": "System Administrator"}, "landing_page": {"type": "255", "_show": "Landing Page", "permissions_read": "System Administrator", "permissions_create": "System Administrator", "permissions_update": "System Administrator"}}, "_projectName": "maker_mike"}') ON DUPLICATE KEY UPDATE id = id;