#DROP DATABASE IF EXISTS maker_mike;
CREATE DATABASE IF NOT EXISTS maker_mike;
USE maker_mike;
CREATE TABLE IF NOT EXISTS project(id int NOT NULL AUTO_INCREMENT, name varchar(255), config JSON, description varchar(255), primary key(id));
CREATE TABLE IF NOT EXISTS settings(id int NOT NULL AUTO_INCREMENT, name varchar(255), value varchar(1024), primary key(id));
CREATE TABLE IF NOT EXISTS user_type(id int NOT NULL AUTO_INCREMENT, name varchar(255), landing_page varchar(255), primary key(id));
CREATE TABLE IF NOT EXISTS user(id int NOT NULL AUTO_INCREMENT, user varchar(255), pass varchar(255), type int, foreign key(type) references user_type(id), primary key(id));

INSERT INTO user_type(id, name, landing_page) VALUES (1, 'System Administrator', 'index.php') ON DUPLICATE KEY UPDATE id = id;
INSERT INTO user_type(id, name, landing_page) VALUES (2, 'User', 'index.php') ON DUPLICATE KEY UPDATE id = id;
INSERT INTO user(id, user, pass, type ) VALUES (1, 'admin',  'admin', 1) ON DUPLICATE KEY UPDATE id = id;
INSERT INTO user(id, user, pass, type ) VALUES (2, 'user',  'user', 2) ON DUPLICATE KEY UPDATE id = id;
INSERT INTO project(id, config) VALUES (1, '{"name":"maker_mike","show":"Maker Mike","tables":[{"name":"project","show":"name","columns":[{"name":"name","show":"Name","type":"255","permissions_read":"-","permissions_create":".*","permissions_update":".*"},{"name":"config","show":"Config","type":"JSON","permissions_read":"-","permissions_create":".*","permissions_update":".*"},{"name":"description","show":"Description","type":"255","permissions_read":"-","permissions_create":".*","permissions_update":".*"}],"permissions":{"read":".*","create":".*","delete":".*","update":".*"}},{"name":"settings","show":"name","columns":[{"name":"name","show":"Name","type":"255","permissions_read":"-","permissions_create":".*","permissions_update":".*"},{"name":"value","show":"Value","type":1024,"permissions_read":"-","permissions_create":".*","permissions_update":".*"}],"permissions":{"read":".*","create":".*","delete":".*","update":".*"}},{"name":"user_type","show":"name","columns":[{"name":"name","show":"Name","type":"255","permissions_read":"-","permissions_create":".*","permissions_update":".*"},{"name":"landing_page","show":"Landing Page","type":"255","permissions_read":"-","permissions_create":".*","permissions_update":".*"}],"permissions":{"read":".*","create":".*","delete":".*","update":".*"}},{"name":"user","show":"user","columns":[{"name":"user","show":"User","type":"255","permissions_read":"-","permissions_create":".*","permissions_update":".*"},{"name":"pass","show":"Pass","type":"255","permissions_read":"-","permissions_create":".*","permissions_update":".*"},{"name":"type","show":"Type","type":"user_type","permissions_read":"-","permissions_create":".*","permissions_update":".*"}],"permissions":{"read":".*","create":".*","delete":".*","update":".*"}}]}') ON DUPLICATE KEY UPDATE id = id;