name: miguelp
show: Miguelp.com
tables:
- name: certification
  columns:
  - title
  - description
  - name: image
    type: file
- name: blogEntry
  columns:
  - title
  - name: public
    type: boolean
  - description
  - name: content
    type: 15000
- name: blogImage
  columns:
  - name
  - name: image
    type: file
- name: to_do
  permissions:
    read: System Administrator
- name: temperature
  columns:
  - date
  - celsius
  - sensor